name: deploy

on: [push]

env:
  FIREBASE_API_KEY: "AIzaSyA1QXQiWTcaGE8VtF3zxmLLKcVjGGutI7w"
  FIREBASE_AUTH_DOMAIN: "pokedri-minnnano63.firebaseapp.com"
  FIREBASE_DATABASEURL: "https://pokedri-minnnano63.firebaseio.com"
  FIREBASE_PROJECT_ID: "pokedri-minnnano63"
  FIREBASE_STORAGE_BUCKET: "pokedri-minnnano63.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID: "943360468967"
  FIREBASE_APP_ID: "1:943360468967:web:600853e2b3aa13fde7ff42"
  FIREBASE_MEASUREMENT_ID: "G-JV3VCF42F8"
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  production:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    if: github.ref == 'refs/heads/master'

    steps:
      - name: GCP Authenticate
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '277.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy
        run: |
          gcloud config set project "$FIREBASE_PROJECT_ID"
          gcloud components install beta --quiet
          echo "SKIP"
